#!/usr/bin/python
# -*- coding: utf-8 -*-

"""Program docstring.

Application to control ASRock IPMI (AMI?)

- https://lime-technology.com/forum/index.php?topic=39238.0
- requires ipmitool to be installed on system and "in path"
- ipmitool -H <host> -U <username> -P <password> raw 0x3a 0x01 0x00 0x00 0x28 0x28 0x2d 0x2d 0x00 0x00

"""
__author__ = "Zacharias El Banna"
__version__ = "10.0"
__status__ = "Production"

from sys import argv, exit, path as syspath
from sdcp.devices.IPMI import IPMI


############################ MAIN ############################
#
# Make funtions take host arg (= argv[1])
#

ipmi = IPMI(argv[1])

if (len(argv) == 3) and (argv[2] == "-r"):
 ipmi.print_info("RPM")
elif (len(argv) == 3) and (argv[2] == "-rv"):
 ipmi.print_info("RPM|degrees")
elif len(argv) < 5 or len(argv) > 6 or (argv[2] != "-w"):
 print argv[0] + " <host_ip> -w(ritfans) <rear fan(s) %> <front fan(s) %> [-v(erbose)]"
 print argv[0] + " <host_ip> -r(eadfans)"
 print argv[0] + " <host_ip> -r(eadfans)v(erbose)"
 exit(0)
elif (len(argv) == 6) and (argv[2] == "-w") and (argv[5] == "-v"):
 ipmi.print_info("RPM")
 ipmi.set_fans(argv[3],argv[4])
else:
 ipmi.set_fans(argv[3],argv[4])
