#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Program docstring.

Application to show service info
- upshost
- domain
- servicehosts (list separated by ,)

"""
__author__ = "Zacharias El Banna"
__version__ = "2.0"
__status__ = "Production"

from subprocess import check_output
from sys import path as syspath
syspath.append('/usr/local/sbin')
from Munin import Munin
from WWW import Web

web      = Web('Services Pane')
form     = web.getForm()
upshost  = form.getvalue('upshost',"esxi1")
services = form.getvalue('servicehosts',"services,services2")
svclist  = services.split(',')
domain   = form.getvalue('domain',"stolab")
munin    = Munin('/etc/munin/munin.conf','/mnt/ramdisk/munin/lib/')

web.printCGIHeader()
print "<DIV CLASS='z-system-container'>"

print "<DIV CLASS='z-system'>"
try:
 syslogs = check_output("tail -n 10 /var/log/system/system.log | tac", shell=True)
 netlogs = check_output("tail -n 20 /var/log/network/{}.log | tac".format(domain), shell=True)

 print "<DIV CLASS='z-font-header'>Network Logs</DIV>"
 print "<DIV CLASS='z-logs'><PRE>{}</PRE></DIV>".format(netlogs)

 print "<DIV CLASS='z-font-header'>System Logs</DIV>"
 print "<DIV CLASS='z-logs'><PRE>{}</PRE></DIV>".format(syslogs)
except Exception as err:
 print "<DIV CLASS='z-error'>{}</DIV>".format(str(err))
print "</DIV>"

print "<DIV CLASS='z-munin'><CENTER>"
munin.printHtml("{1}/{0}.{1}/hw_apc_power".format(upshost,domain))
munin.printHtml("{1}/{0}.{1}/hw_apc_time".format(upshost,domain))
munin.printHtml("{1}/{0}.{1}/hw_apc_temp".format(upshost,domain))
print "</CENTER></DIV>"

print "<DIV CLASS='z-system'>"
print "<DIV CLASS='z-munin' style='width:33%; float:left;'>"
print "<DIV CLASS='z-font-header'>DDI Stats</DIV>"
munin.printHtml("{1}/{0}.{1}/pdns_queries".format(svclist[0],domain))
print "<BR>"
munin.printHtml("{1}/{0}.{1}/dhcpd3".format(svclist[0],domain))
print "</DIV>"
print "<DIV CLASS='z-table' style='width:33%; float:left;'>"
web.printURL("http://{}/dns-top.php?type=sites".format(svclist[0]))
print "</DIV>"
print "<DIV CLASS='z-table' style='width:33%;'>"
web.printURL("http://{}/dns-top.php?type=clients".format(svclist[0])) 
print "</DIV>";
print "<BR style='clear: left;'/>"
print "</DIV>"

print "<DIV CLASS='z-system'>"
print "<DIV CLASS='z-font-header'>DHCP Lease List</DIV>"
print "<DIV CLASS='z-logs'>"
web.printURL("http://{0}/dhcp-lease-list.php".format(svclist[0]))
print "</DIV>"
print "</DIV>"

print "<DIV CLASS='z-system'>"
for svc in svclist:
 print "<DIV style='width:" + str(int(100/len(svclist))) + "%; float:left'>"
 print "<DIV CLASS='z-font-header'>System Logs for {}.{}</DIV>".format(svc,domain)
 print "<DIV CLASS='z-logs'>"
 web.printURL("http://{}/systemlog.php".format(svc))
 print "</DIV>"
 print "</DIV>"
print "<BR STYLE='clear:left;'>"
print "</DIV>"

#
# End Div
#
print "</DIV>"

